name: Run lint checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [full, fdroid]
    name: Run lint checks (${{ matrix.version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check code style with ktfmt
        run: ./gradlew ktfmtCheck
      - name: Capitalize version name
        id: capitalize-version
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.version }}
      - name: Run lint checks
        run: ./gradlew lint${{ steps.capitalize-version.outputs.capitalized }}Debug